version: '3.7'
services:
  app:
    container_name: app
    build:
      context: ./
    restart: always
    ports:
      - '${PRODUCTION_PORT}:${PRODUCTION_PORT}'
    environment:
      NODE_ENV: production
